#!/usr/bin/with-contenv bash
if [ ! -f /config/wg0.conf ]; then
    echo "Installing pia-wg-config"
    
    curl -OL https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin:/root/go/bin

    go install github.com/kylegrantlucas/pia-wg-config@latest

    pia-wg-config -o /config/wg0.conf -r $PIA_REGION $PIA_USER $PIA_PASS
fi
